# Generated by Django 3.1.5 on 2021-01-23 21:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('enrolled_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enrolled date')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last seen')),
                ('online_status', models.BooleanField(default=True, verbose_name='Online status')),
                ('tasks', models.IntegerField(default=0, verbose_name='Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('enrolled_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enrolled date')),
                ('comments', models.TextField(max_length=200, verbose_name='Comments')),
                ('ascDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infobackendapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=300, verbose_name='Scan TE Token')),
                ('ascPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infobackendapp.patient')),
            ],
        ),
    ]
