# Generated by Django 3.1.5 on 2021-01-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobackendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='username.username', max_length=50, verbose_name='username'),
            preserve_default=False,
        ),
    ]
