# Generated by Django 3.1.5 on 2021-01-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobackendapp', '0004_auto_20210124_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='A', max_length=30, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='A', max_length=30, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='A', max_length=30, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='A', max_length=30, verbose_name='Last name'),
            preserve_default=False,
        ),
    ]
