# Generated by Django 3.1.5 on 2021-01-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobackendapp', '0005_auto_20210124_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nino',
            field=models.CharField(default='Not Set', max_length=9, verbose_name='National Insurance Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(default='Not Set', max_length=30, verbose_name='Title'),
        ),
    ]
