# Generated by Django 3.1.5 on 2021-01-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobackendapp', '0007_auto_20210126_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nino',
            field=models.CharField(max_length=9, unique=True, verbose_name='National Insurance Number'),
        ),
    ]
