# Generated by Django 3.1.5 on 2021-02-09 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infobackendapp', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='algorithm',
            field=models.CharField(default='NS', max_length=5, verbose_name='Algorithm Used'),
        ),
        migrations.AddField(
            model_name='scan',
            name='comment',
            field=models.TextField(default='Not Set', max_length=300, verbose_name='Doctors Comments'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Scan Token'),
        ),
    ]
