# Generated by Django 3.1.5 on 2021-02-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobackendapp', '0010_auto_20210209_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=10, verbose_name='Scan Status'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='algorithm',
            field=models.CharField(choices=[('NS', 'NOT SET'), ('SVC', 'Simple Support Vector Machine')], default='NS', max_length=10, verbose_name='Algorithm Used'),
        ),
    ]
