# Generated by Django 3.1.5 on 2021-02-11 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infobackendapp', '0011_auto_20210210_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
