# Generated by Django 3.1.5 on 2021-02-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infobackendapp', '0012_scan_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='algorithm',
        ),
    ]
